# Default values for kubernetes-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pod:
  name: nginx
  image: nginx
  pullPolicy: IfNotPresent
  labels:
    app: nginx
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  ports: 80
  volumeMounts:
    - mountPath: "/var/www/html"
      name: mypd
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: pvc-1
 
  persistentVolume:
    - name: pv-1
      storage: 1Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      storageClassName: slow
      hostPath: /data

  persistentVolumeClaim:
    - name: pvc-1
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      storage: 1Gi
      storageClassName: slow

  service:
    name: nginx-service
    type: NodePort
    # selector:
    #   app: my-app
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
