dockerServices:
  - name: web
    # enabled: false
    build:
      context: vuejs
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./vuejs:/project
      - /project/node_modules
    command:
      - "sleep 5900"